extends Node

enum PowerUpType {
	NONE = 0, 
	PADDLE_SPEED_DOWN = 1, # 1
	PADDLE_SPEED_UP = 2, # 2
	LIFE_UP = 3, # 3
	LIFE_DOWN = 4, # 4
	BALL_SPEED_UP = 5, # 5
	BALL_SPEED_DOWN = 6, # 6
	BALL_SIZE_DECREASE = 7, # 7
	BALL_SIZE_INCREASE = 8, # 8
	BALL_MULTIPLIER = 9, # 9
	# CHANGE_THEME, # 10
}
